const { writeFileSync } = require('fs');
const { root } = require('./themeDesignerVariables');
const PATHS = require('../../../../config/paths');
const path = require('path');

const variables = Object.keys(root);

let fileContent = `/* 
 * ### WARNING ### 
 * This is an autogenerated file, do not change manually. 
 * In order to recreate this file, please run 'node packages/base/scripts/cssVariables/parse.js'
 */

`;

fileContent += 'export const ThemingParameters = {\n';
for (const variable of variables) {
  fileContent += `  '${variable}': 'var(--${variable})',\n`;
}
fileContent += '}\n';

writeFileSync(path.join(PATHS.packages, 'base', 'src', 'styling', 'themingParameters.ts'), fileContent);
